version: '3.8'

services:
  manatalassignment:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - ../manataltest/.env

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:manataldb

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  manataldb:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - manatal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: manatal
      POSTGRES_DB: manataldb
      POSTGRES_PASSWORD: manatalassignment

    ports:
      - 5432:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  manatal-data:
