# Generated by Django 5.1.3 on 2024-11-16 07:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=8)),
                ("email address", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=14)),
            ],
        ),
    ]
