# Generated by Django 5.1.3 on 2024-11-16 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_rename_email_address_users_email_users_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="users",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
