# Generated by Django 5.1.3 on 2024-11-17 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_users_created_at_alter_users_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="uuid",
            new_name="id",
        ),
    ]
